main: src/main.cpp src/EctoPath.cpp src/EctoPath.h src/EctoPathOptimize.cpp src/EctoPathOptimize.h
	g++  -fopenmp -o test src/main.cpp src/EctoPath.cpp src/EctoPath.h src/EctoPathOptimize.cpp src/EctoPathOptimize.h -I src/
